FROM node:20-alpine as builder
WORKDIR /app
ARG VITE_WEB3FORMS_ACCESS_KEY
ENV VITE_WEB3FORMS_ACCESS_KEY=$VITE_WEB3FORMS_ACCESS_KEY
COPY . .
RUN npm install
RUN npm run build

FROM nginx:1.25.4-alpine-slim as prod
WORKDIR /app
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf  /etc/nginx/conf.d
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]